var h;h||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,r="undefined"!=typeof WorkerGlobalScope,ba="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,t=(a,b)=>{throw b;},u="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?u=__filename:r&&(u=self.location.href);var w="",y,z;
if(ba){var fs=require("fs");w=__dirname+"/";z=a=>{a=B(a)?new URL(a):a;return fs.readFileSync(a)};y=async a=>{a=B(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);t=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||r){try{w=(new URL(".",u)).href}catch{}r&&(z=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});y=async a=>{if(B(a))return new Promise((c,d)=>{var e=
new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}console.log.bind(console);var C=console.error.bind(console),D,E=!1,F,B=a=>a.startsWith("file://"),ca,da,G,H,I,J,K,ea,fa,ha,ja,L=0,O=null;
function ka(a){h.onAbort?.(a);a="Aborted("+a+")";C(a);E=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var la;async function ma(a){if(!D)try{var b=await y(a);return new Uint8Array(b)}catch{}if(a==la&&D)a=new Uint8Array(D);else if(z)a=z(a);else throw"both async and sync fetching of the wasm failed";return a}async function na(a,b){try{var c=await ma(a);return await WebAssembly.instantiate(c,b)}catch(d){C(`failed to asynchronously prepare wasm: ${d}`),ka(d)}}
async function oa(a){var b=la;if(!D&&"function"==typeof WebAssembly.instantiateStreaming&&!B(b)&&!ba)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){C(`wasm streaming compile failed: ${d}`),C("falling back to ArrayBuffer instantiation")}return na(b,a)}class pa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var qa=a=>{for(;0<a.length;)a.shift()(h)},ra=[],sa=[],ta=()=>{var a=h.preRun.shift();sa.push(a)},P=!0,Q=a=>{for(var b="";;){var c=G[a++];if(!c)return b;b+=String.fromCharCode(c)}},R={},S={},T={},U=class extends Error{constructor(a){super(a);this.name="BindingError"}},ua=a=>{throw new U(a);};
function va(a,b,c={}){var d=b.name;if(!a)throw new U(`type "${d}" must have a positive integer typeid pointer`);if(S.hasOwnProperty(a)){if(c.F)return;throw new U(`Cannot register type '${d}' twice`);}S[a]=b;delete T[a];R.hasOwnProperty(a)&&(b=R[a],delete R[a],b.forEach(e=>e()))}function V(a,b,c={}){return va(a,b,c)}
var wa=(a,b,c)=>{switch(b){case 1:return c?d=>da[d]:d=>G[d];case 2:return c?d=>H[d>>1]:d=>I[d>>1];case 4:return c?d=>J[d>>2]:d=>K[d>>2];case 8:return c?d=>ha[d>>3]:d=>ja[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},xa=[],W=[0,1,,1,null,1,!0,1,!1,1],ya=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=xa.pop()||W.length;W[b]=a;W[b+1]=1;return b}};function za(a){return this.fromWireType(K[a>>2])}
var Aa={name:"emscripten::val",fromWireType:a=>{if(!a)throw new U(`Cannot use deleted val. handle = ${a}`);var b=W[a];9<a&&0===--W[a+1]&&(W[a]=void 0,xa.push(a));return b},toWireType:(a,b)=>ya(b),C:8,readValueFromPointer:za,B:null},Da=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(ea[c>>2])};case 8:return function(c){return this.fromWireType(fa[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Ea=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};
function Fa(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].B)return!0;return!1}
var Ga=(a,b)=>{var c=h;if(void 0===c[a].A){var d=c[a];c[a]=function(...e){if(!c[a].A.hasOwnProperty(e.length))throw new U(`Function '${b}' called with an invalid number of arguments (${e.length}) - expects one of (${c[a].A})!`);return c[a].A[e.length].apply(this,e)};c[a].A=[];c[a].A[d.D]=d}},Ha=(a,b,c)=>{if(h.hasOwnProperty(a)){if(void 0===c||void 0!==h[a].A&&void 0!==h[a].A[c])throw new U(`Cannot register public name '${a}' twice`);Ga(a,a);if(h[a].A.hasOwnProperty(c))throw new U(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
h[a].A[c]=b}else h[a]=b,h[a].D=c},Ia=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(K[b+4*d>>2]);return c},Ja=class extends Error{constructor(a){super(a);this.name="InternalError"}},Ka,La=(a,b)=>{a=Q(a);var c=Ka.get(b);if("function"!=typeof c)throw new U(`unknown function pointer with signature ${a}: ${b}`);return c};class Ma extends Error{}
var Oa=a=>{a=Na(a);var b=Q(a);X(a);return b},Pa=(a,b)=>{function c(g){e[g]||S[g]||(T[g]?T[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new Ma(`${a}: `+d.map(Oa).join([", "]));},Qa=(a,b)=>{function c(f){f=b(f);if(f.length!==d.length)throw new Ja("Mismatched type converter count");for(var m=0;m<d.length;++m)V(d[m],f[m])}var d=[];d.forEach(f=>T[f]=a);var e=Array(a.length),g=[],l=0;a.forEach((f,m)=>{S.hasOwnProperty(f)?e[m]=S[f]:(g.push(f),R.hasOwnProperty(f)||(R[f]=[]),R[f].push(()=>
{e[m]=S[f];++l;l===g.length&&c(e)}))});0===g.length&&c(e)},Ra=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},Sa=new TextDecoder,Ta=new TextDecoder("utf-16le"),Ua=(a,b)=>{a>>=1;b=a+b/2;for(var c=a;!(c>=b)&&I[c];)++c;return Ta.decode(I.subarray(a,c))},Va=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)H[b>>1]=a.charCodeAt(e),b+=2;H[b>>1]=0;return b-d},Wa=a=>2*a.length,Xa=(a,b)=>{for(var c="",d=0;!(d>=b/4);d++){var e=J[a+4*d>>
2];if(!e)break;c+=String.fromCodePoint(e)}return c},Ya=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.codePointAt(e);65535<g&&e++;J[b>>2]=g;b+=4;if(b+4>c)break}J[b>>2]=0;return b-d},Za=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},$a=0,Y={},ab=a=>{F=a;P||0<$a||(h.onExit?.(a),E=!0);t(a,new pa(a))},bb=a=>{if(!E)try{if(a(),!(P||0<$a))try{F=a=F,ab(a)}catch(b){b instanceof pa||"unwind"==b||t(1,b)}}catch(b){b instanceof pa||"unwind"==
b||t(1,b)}};h.noExitRuntime&&(P=h.noExitRuntime);h.printErr&&(C=h.printErr);h.wasmBinary&&(D=h.wasmBinary);
var Na,cb,db,X,eb={n:()=>ka(""),e:(a,b,c,d,e)=>{b=Q(b);d=0n===d;let g=l=>l;if(d){const l=8*c;g=f=>BigInt.asUintN(l,f);e=g(e)}V(a,{name:b,fromWireType:g,toWireType:(l,f)=>{"number"==typeof f&&(f=BigInt(f));return f},C:8,readValueFromPointer:wa(b,c,!d),B:null})},i:(a,b,c,d)=>{b=Q(b);V(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,g){return g?c:d},C:8,readValueFromPointer:function(e){return this.fromWireType(G[e])},B:null})},g:a=>V(a,Aa),d:(a,b,c)=>{b=Q(b);V(a,{name:b,fromWireType:d=>
d,toWireType:(d,e)=>e,C:8,readValueFromPointer:Da(b,c),B:null})},f:(a,b,c,d,e,g,l)=>{var f=Ia(b,c);a=Q(a);a=Ra(a);e=La(d,e);Ha(a,function(){Pa(`Cannot call ${a} due to unbound types`,f)},b-1);Qa(f,m=>{var k=[m[0],null].concat(m.slice(1));m=a;var p=a;var x=e,n=k.length;if(2>n)throw new U("argTypes array size mismatch! Must at least get return value and 'this' types!");var A=null!==k[1]&&!1,M=Fa(k),Ba="void"!==k[0].name;x=[p,ua,x,g,Ea,k[0],k[1]];for(var v=0;v<n-2;++v)x.push(k[v+2]);if(!M)for(v=A?1:
2;v<k.length;++v)null!==k[v].B&&x.push(k[v].B);M=Fa(k);v=k.length-2;var q=[],N=["fn"];A&&N.push("thisWired");for(n=0;n<v;++n)q.push(`arg${n}`),N.push(`arg${n}Wired`);q=q.join(",");N=N.join(",");q=`return function (${q}) {\n`;M&&(q+="var destructors = [];\n");var Ca=M?"destructors":"null",ia="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");A&&(q+=`var thisWired = classParam['toWireType'](${Ca}, this);\n`);for(n=0;n<v;++n)q+=`var arg${n}Wired = argType${n}['toWireType'](${Ca}, arg${n});\n`,
ia.push(`argType${n}`);q+=(Ba||l?"var rv = ":"")+`invoker(${N});\n`;if(M)q+="runDestructors(destructors);\n";else for(n=A?1:2;n<k.length;++n)A=1===n?"thisWired":"arg"+(n-2)+"Wired",null!==k[n].B&&(q+=`${A}_dtor(${A});\n`,ia.push(`${A}_dtor`));Ba&&(q+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [fb,gb]=[ia,q+"}\n"];k=(new Function(...fb,gb))(...x);p=Object.defineProperty(k,"name",{value:p});k=b-1;if(!h.hasOwnProperty(m))throw new Ja("Replacing nonexistent public symbol");void 0!==
h[m].A&&void 0!==k?h[m].A[k]=p:(h[m]=p,h[m].D=k);return[]})},b:(a,b,c,d,e)=>{b=Q(b);let g=f=>f;if(0===d){var l=32-8*c;g=f=>f<<l>>>l;e=g(e)}V(a,{name:b,fromWireType:g,toWireType:(f,m)=>m,C:8,readValueFromPointer:wa(b,c,0!==d),B:null})},a:(a,b,c)=>{function d(g){return new e(da.buffer,K[g+4>>2],K[g>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=Q(c);V(a,{name:c,fromWireType:d,C:8,readValueFromPointer:d},{F:!0})},
h:(a,b)=>{b=Q(b);V(a,{name:b,fromWireType:function(c){for(var d=K[c>>2],e=c+4,g,l=e,f=0;f<=d;++f){var m=e+f;if(f==d||0==G[m]){if(l){for(var k=l+(m-l),p=l;!(p>=k)&&G[p];)++p;l=Sa.decode(G.subarray(l,p))}else l="";void 0===g?g=l:(g+=String.fromCharCode(0),g+=l);l=m+1}}X(c);return g},toWireType:function(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e,g="string"==typeof d;if(!(g||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new U("Cannot pass non-string to std::string");var l;if(g)for(e=
l=0;e<d.length;++e){var f=d.charCodeAt(e);127>=f?l++:2047>=f?l+=2:55296<=f&&57343>=f?(l+=4,++e):l+=3}else l=d.length;e=l;l=cb(4+e+1);f=l+4;K[l>>2]=e;if(g){if(g=f,f=e+1,e=G,0<f){f=g+f-1;for(var m=0;m<d.length;++m){var k=d.codePointAt(m);if(127>=k){if(g>=f)break;e[g++]=k}else if(2047>=k){if(g+1>=f)break;e[g++]=192|k>>6;e[g++]=128|k&63}else if(65535>=k){if(g+2>=f)break;e[g++]=224|k>>12;e[g++]=128|k>>6&63;e[g++]=128|k&63}else{if(g+3>=f)break;e[g++]=240|k>>18;e[g++]=128|k>>12&63;e[g++]=128|k>>6&63;e[g++]=
128|k&63;m++}}e[g]=0}}else G.set(d,f);null!==c&&c.push(X,l);return l},C:8,readValueFromPointer:za,B(c){X(c)}})},c:(a,b,c)=>{c=Q(c);if(2===b){var d=Ua;var e=Va;var g=Wa;var l=f=>I[f>>1]}else 4===b&&(d=Xa,e=Ya,g=Za,l=f=>K[f>>2]);V(a,{name:c,fromWireType:f=>{for(var m=K[f>>2],k,p=f+4,x=0;x<=m;++x){var n=f+4+x*b;if(x==m||0==l(n))p=d(p,n-p),void 0===k?k=p:(k+=String.fromCharCode(0),k+=p),p=n+b}X(f);return k},toWireType:(f,m)=>{if("string"!=typeof m)throw new U(`Cannot pass non-string to C++ string type ${c}`);
var k=g(m),p=cb(4+k+b);K[p>>2]=k/b;e(m,p+4,k+b);null!==f&&f.push(X,p);return p},C:8,readValueFromPointer:za,B(f){X(f)}})},o:(a,b)=>{b=Q(b);V(a,{G:!0,name:b,C:0,fromWireType:()=>{},toWireType:()=>{}})},k:()=>{P=!1;$a=0},l:(a,b)=>{Y[a]&&(clearTimeout(Y[a].id),delete Y[a]);if(!b)return 0;var c=setTimeout(()=>{delete Y[a];bb(()=>db(a,performance.now()))},b);Y[a]={id:c,H:b};return 0},m:()=>{ka("OOM")},j:ab},Z;
(async function(){function a(c){Z=c.exports;ca=Z.p;c=ca.buffer;da=new Int8Array(c);H=new Int16Array(c);G=new Uint8Array(c);I=new Uint16Array(c);J=new Int32Array(c);K=new Uint32Array(c);ea=new Float32Array(c);fa=new Float64Array(c);ha=new BigInt64Array(c);ja=new BigUint64Array(c);Ka=Z.u;c=Z;Na=c.r;cb=c.s;db=c.t;X=c.v;L--;h.monitorRunDependencies?.(L);0==L&&O&&(c=O,O=null,c());return Z}L++;h.monitorRunDependencies?.(L);var b={a:eb};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,
e)=>{c(a(d,e))})});la??=h.locateFile?h.locateFile("JQen.wasm",w):w+"JQen.wasm";return a((await oa(b)).instance)})();
function hb(){function a(){h.calledRun=!0;if(!E){Z.q();h.onRuntimeInitialized?.();if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var b=h.postRun.shift();ra.push(b)}qa(ra)}}if(0<L)O=hb;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)ta();qa(sa);0<L?O=hb:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);a()},1)):a()}}
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();hb();
